meta_name: "Specialty Coffee Diary"
meta_title: "Specialty Coffee Diary | Never forget your favorite cups anymore"
meta_description: "While accurate brew recipes or origin's details are already a pretty nerdy topic, they are hard to remember most of the times without taking notes.
                  So this app should help you bookmark you're favorite coffees, as well as discovering new ones you might want to try soon."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
